# Generated by Django 6.1.1 on 2026-09-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=160)),
                ('degree', models.CharField(max_length=160)),
                ('period', models.CharField(help_text='Example: 2023-2026 ya Ongoing (2026)', max_length=60)),
                ('score', models.CharField(blank=True, help_text='Example: CGPA 7.97 ya 78.8%', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False, help_text='Abhi padh rahi ho to tick karo.')),
                ('order', models.PositiveIntegerField(default=10, help_text='Chhota number upar dikhta hai (latest ko 1 do).')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=160)),
                ('period', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, help_text='Ek line = ek point.')),
                ('order', models.PositiveIntegerField(default=10, help_text='Chhota number upar dikhta hai (latest ko 1 do).')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Khushbu Patidar', max_length=100)),
                ('headline', models.CharField(default='Python / Django Developer', help_text='Browser tab aur footer me dikhta hai. Example: Python / Django Developer', max_length=150)),
                ('typed_roles', models.CharField(blank=True, help_text='Comma se alag karo. Hero me "I\'m a ..." ke baad ek-ek karke type hote hain.', max_length=300)),
                ('tagline', models.TextField(blank=True, help_text='Naam ke neeche chhoti si line.')),
                ('about', models.TextField(blank=True, help_text='About section ka text. Paragraphs ke beech khaali line chhodo.')),
                ('photo', models.ImageField(blank=True, help_text='Hero section wali photo (portrait best rehti hai).', upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='Naya PDF upload karke Save karo. Site ke View/Download buttons turant naya resume dikhayenge.', upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('open_to_work', models.BooleanField(default=True, help_text="On rakho to hero me green 'available' badge dikhega.")),
                ('availability_text', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile & resume',
                'verbose_name_plural': 'Profile & resume',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Example: Recipe Generator Platform', max_length=140)),
                ('description', models.TextField(help_text='2-3 line ka short summary.')),
                ('highlights', models.TextField(blank=True, help_text='Hover par dikhne wale points. Ek line = ek point.')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma se alag karo: Python, Django, MySQL', max_length=250)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot. Nahi doge to colour cover + icon dikhega.', upload_to='projects/')),
                ('icon', models.CharField(blank=True, default='✨', help_text='Cover par dikhne wala emoji (jab screenshot na ho).', max_length=8)),
                ('accent', models.CharField(choices=[('violet', 'Violet'), ('sun', 'Yellow'), ('coral', 'Coral'), ('mint', 'Mint'), ('sky', 'Sky blue')], default='violet', max_length=10)),
                ('order', models.PositiveIntegerField(default=10, help_text='Chhota number pehle dikhta hai.')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools & Platforms'), ('other', 'Other')], default='other', max_length=20)),
                ('detail', models.CharField(blank=True, help_text='Optional. Skill par hover karne par ye chhoti si info dikhti hai.', max_length=160)),
                ('is_highlight', models.BooleanField(default=False, help_text='Hero me photo ke paas sticker ki tarah dikhao (3-4 rakhna best hai).')),
                ('order', models.PositiveIntegerField(default=10, help_text='Chhota number pehle dikhta hai.')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
